
#include "buildversion.h"
#include "defs_version.h"

// #defines of details of the build set up (flags,
// repo number, etc). This isn't a real file, SConscript generates it and it
// probably gets placed in $PLATFORM_build/. By including this file here and
// only here we make sure that updating src or changing the build flags doesn't
// force a rebuild of everything
#include "build.h"

// Generated by SCons
// saves the bzr info for case of tarball build without bzr info present
#include "lastbzrbuild.h"


#ifndef BUILD_BRANCH
 #ifdef LAST_BZR_BUILD_BRANCH
  #define BUILD_BRANCH LAST_BZR_BUILD_BRANCH
 #endif
#endif

#ifndef BUILD_REV
 #ifdef LAST_BZR_BUILD_REV
  #define   LAST_BZR_BUILD_REV
  #define BUILD_BZR "last bzr"
 #else
  #error BUILD_BZR undefined
 #endif
#else
 #define BUILD_BZR "bzr"
#endif


// static
const char* BuildVersion::versionName() {
    return VERSION;
}

// static
const char* BuildVersion::buildInfoFormatted() {
    // e.g.:1.11.0-alpha2 "(bzr daschuer~daschuers-trunk r2993+; built on: Jun  4 2012 @ 22:26:52; flags: hid hifieq ipod mad optimize=2 qdebug shoutcast tagreader test vamp verbose vinylcontrol)"

    return (VERSION " ("
            BUILD_BZR " "
#ifdef BUILD_BRANCH
            BUILD_BRANCH " "
#endif
            "r" BUILD_REV "; "
            "built on: " __DATE__ " @ " __TIME__ "; "
            "flags: " BUILD_FLAGS ")"
            );
}

// static
const char* BuildVersion::versionLable() {
    // e.g.: "1.11.0-alpha2 (bzr daschuer~daschuers-trunk r2993+)"

    return (VERSION " ("
            BUILD_BZR " "
#ifdef BUILD_BRANCH
            BUILD_BRANCH " "
#endif
            "r" BUILD_REV ")"
            );
}

